#include "Action.hpp"
#include <map>

const std::map<Action, std::string> action_to_string_map{
    action_to_string_map_macro(halt),
    action_to_string_map_macro(pc_cnt),
    action_to_string_map_macro(mar_cnt),
    action_to_string_map_macro(sp_dec),
    action_to_string_map_macro(sp_inc),
    action_to_string_map_macro(halt),
    action_to_string_map_macro(pc_cnt),
    action_to_string_map_macro(mar_cnt),
    action_to_string_map_macro(sp_dec),
    action_to_string_map_macro(sp_inc),
    action_to_string_map_macro(pc_addr),
    action_to_string_map_macro(mar_addr),
    action_to_string_map_macro(sp_addr),
    action_to_string_map_macro(a_bout),
    action_to_string_map_macro(b_bout),
    action_to_string_map_macro(x_bout),
    action_to_string_map_macro(y_bout),
    action_to_string_map_macro(z_bout),
    action_to_string_map_macro(pc_lo_bout),
    action_to_string_map_macro(pc_hi_bout),
    action_to_string_map_macro(mar_lo_bout),
    action_to_string_map_macro(mar_hi_bout),
    action_to_string_map_macro(sp_lo_bout),
    action_to_string_map_macro(sp_hi_bout),
    action_to_string_map_macro(keyb_bout),
    action_to_string_map_macro(flags_bout),
    action_to_string_map_macro(f_alu_bout),
    action_to_string_map_macro(a_write),
    action_to_string_map_macro(b_write),
    action_to_string_map_macro(x_write),
    action_to_string_map_macro(y_write),
    action_to_string_map_macro(z_write),
    action_to_string_map_macro(pc_lo_write),
    action_to_string_map_macro(pc_hi_write),
    action_to_string_map_macro(mar_lo_write),
    action_to_string_map_macro(mar_hi_write),
    action_to_string_map_macro(sp_lo_write),
    action_to_string_map_macro(sp_hi_write),
    action_to_string_map_macro(ir_write),
    action_to_string_map_macro(ir2_write),
    action_to_string_map_macro(mem_read),
    action_to_string_map_macro(mem_write),
    action_to_string_map_macro(x_shift_left),
    action_to_string_map_macro(y_shift_left),
    action_to_string_map_macro(x_shift_right),
    action_to_string_map_macro(y_shift_right),
    action_to_string_map_macro(flag_direct),
    action_to_string_map_macro(flag_carry),
    action_to_string_map_macro(flag_eq),
    action_to_string_map_macro(flag_zero),
    action_to_string_map_macro(flag_6),
    action_to_string_map_macro(flag_5),
    action_to_string_map_macro(flag_7),
    action_to_string_map_macro(flag_8),
    action_to_string_map_macro(flag_write_alu),
    action_to_string_map_macro(reset)};

const std::string &actionToString(const Action &action) {
  return action_to_string_map.at(action);
}
