#include "TemplateDefinitions.hpp"
#include "Opcode.hpp"
#include "TemplateGenerators.hpp"
#include "Templates.hpp"
#include <memory>

IstrTemplateType test_template = {
    {pc_cnt, mar_cnt}, {sp_dec, sp_inc}, {}, {}, {},
};

// global instance of the instruction set generated by the function below
static InstructionSet istr_set;

void instantiateTemplates() {
  // TODO: implement all the different templates
  istr_set.instructions[0] = std::make_unique<Instruction>(test_template);
}

IstrTemplateType opcodeToTemplate(const Opcode &opcode) {
  // TODO: implement
  return istr_set.opcodeToTemplate(opcode);
}
