WHITESPACE = _{ " " | "\t" }
COMMENT    = _{ Newline* ~ ";" ~ (!NEWLINE ~ ANY)* }
// COMMENT    = _{ "####" }
// Comment    = _{ Newline* ~ WHITESPACE* ~ ";" ~ (!NEWLINE ~ ANY)* }


KEYWORD = @{
    "fn" | "true" | "false" | "int" | "bool" | "return"
}

// Program is a sequence of statements/expressions
Program = _{ SOI ~ (Statement)* ~ Newline* ~ EOI }

Newline = _{ NEWLINE }

// Statements
Statement             = { Newline* ~ ((FunctionCall ~ Newline*) | FunctionStatement | ReturnStatement | LabelStatement | BlockLabel | Block | InstructionStatement) }


ExprParameters = { ExprParameter ~ ("," ~ ExprParameter)* }
ExprParameter  = _{ Expr }

InstructionStatement  = { InstructionLabel ~ ExprParameters? ~ Newline+ }
InstructionLabel      = { Identifier }

FunctionCall = { FunctionCallName ~ "(" ~ ExprParameters? ~ ")" }
FunctionCallName      = { Identifier }
FunctionCallParameter  = _{ Expr }



ReturnStatement = { "return" ~ ReturnParameter ~ Newline* }
ReturnParameter = _{ Block | Expr }

TypedParameter = { Identifier ~ ":" ~ Type }

FunctionStatement = { "fn" ~ FunctionName ~ "(" ~ FunctionParameters? ~ ")" ~ FunctionReturnType? ~ Newline* ~ Block }
FunctionParameters = { FunctionParameter ~ ("," ~ FunctionParameter)* }
FunctionName      = { Identifier }
FunctionParameter  = _{ TypedParameter }
FunctionReturnType = { "->" ~ Type }

// label:
LabelStatement = { LabelIdentifier ~ ":" ~ Newline+ }

/// label { /* body (statements) */ }
BlockLabel = { LabelIdentifier ~ Newline* ~ Block }

// atomic to avoid having to dig into identifier
LabelIdentifier = { Identifier }

Block = { "{"  ~ Newline+ ~ Statement* ~ "}" }

// Arithmetic operators
add = { "+" }
subtract = { "-" }
multiply = { "*" }
divide = { "/" }
modulo = { "%" }
power = { "**" }

shift_left = { "<<" }
shift_right = { ">>" }
bit_and = { "&" }
bit_xor = { "^" }
bit_or = { "|" }


// Comparison operators
eq = { "==" }
ne = { "!=" }
le = { "<=" }  // Must come before "<" to avoid tokenizing "<=" as "<" + "=" in the `infix_op` rule later
ge = { ">=" }  // Must come before ">" to avoid tokenizing ">=" as ">" + "=" in the `infix_op` rule later
lt = { "<" }
gt = { ">" }

// Logical operators
logical_and = { "&&" }
logical_or = { "||" }

// Expression structure for Pratt parser
Expr = { prefix_op? ~ Primary ~ (infix_op ~ prefix_op? ~ Primary )* }

// All infix operations that the Pratt parser will handle
infix_op = _{
    add | subtract | multiply | divide | modulo | power |
    shift_left | shift_right |
    eq | ne | le | ge | lt | gt | logical_and | logical_or
	// must do bitwise after logical otherwise bit consumes logical
	| bit_and | bit_or
}

prefix_op = _{ negation | bit_negation | logical_not }

// Unary operators
negation = { "-" }
bit_negation = { "~" }
logical_not = { "!" }

// Primary expressions
Primary = _{ FunctionCall | Literal | (Identifier ~ !":") | "(" ~ Expr ~ ")" }

// Literals
// Hex must have higher precedence otherwise gets recognized as int
Literal =  { Bool | Hexadecimal | Int  | String | Character }

HexadecimalDigit = @{ ASCII_HEX_DIGIT+ }
Hexadecimal       = { ^"0x" ~ HexadecimalDigit }

Type = { U16Type | U8Type | I16Type | I8Type | IntType | BoolType | LabelType | AddrType }
U16Type = { "u16" }
U8Type = { "u8" }
I16Type = { "i16" }
I8Type = { "i8" }
IntType = { "int" }
BoolType = { "bool" }
LabelType = { "Label" }
AddrType = { "Address" }

Int     = @{ ASCII_DIGIT+ }

Bool    = @{ "true" | "false" }
String = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
Character = @{ "'" ~ ("\\"? ~ ANY) ~ "'" }

// Identifiers (variable/function names)
Identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }
